apiVersion: apps/v1 
kind: Deployment
metadata:
  name: datacollector-service
  labels:
    app: sensornet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sensornet
  template:
    metadata:
      labels:
        app: sensornet
    spec:
      containers:
      - name: collector
        image: datacollector:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
          requests:
            memory: "256Mi"
            cpu: "0.5"